spring.application.name=Rootly
# Updated Spring Boot configuration property
server.port=8080
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
spring.mongodb.uri=mongodb+srv://applicationf695_db_user:5KWctv2cK5vgcxwX@rootlycluster.qf3pa74.mongodb.net/rootly_db?appName=RootlyCluster
spring.data.mongodb.auto-index-creation=true
#UserName=applicationf695_db_user
#password=5KWctv2cK5vgcxwX